sudo: required
language: bash
env:
  global:
  - BUILD_NAME: ExampleProjectName
  - GH_USER: shadowmanu
  - GH_REPO: unity-travis-ci-test
  - secure: cO/z4HPREy359eZNnLTAaCV9K58GeDja/XDnTjVMyzDqEclb7X75a8DhUdhGnkP0JlQweFWN0Im+37ys5QXuL2LtHXNM/TQzA3PLYxI8yGHPDLhWTr4xE+i3Q1mUUl+5eBRirlZtw/1gQicZHgy56a88kIQzqQd7mdwhsJLSxTMBBQqJnIVRDoDCr049JhUoPruXUzG/X7dgHFmvEAdBVVbOb8EAUQRs7qcwyvgxVC/CrzRotdezL0UpM69NraGgTmbyY6USmc23zJLhZG8Dgex0t0AVTVhZE8/gFZA5x35sozoL01Dmt89ooPhDCLSlpDdVVGyu2rcJ5FTDHs1a8CUKrSHJy1NhwgmWIPayfR6pvxaqyCoaBLnl67hBxkZde7HH9AIOZwzmNJ9W0LEDDL6oIKgwKWoxkNywvA4tQtjgcAeqp8eVnEwQlZ4ooUpkiNvIdbQpDbAWBPMV9V+2++MCORPcOKE9ghTkWTHKzKSUiNS/vzrkOl21AmtH5G12WWmzD7Zga9ss1r/OXXi9KF5ZqVaJwmTu9T393mhFq/18fkBkYq/rRpUPNZRoYMLrmJMAv0EoEA9OqWe+YDZeINByGVkcC+02ieQOGAEU86a3WyDo8EWs/K/8Un+SJUKC/D+HidUB9uvsJ2hbSvXPNqO9vgqnsobSfXOt7zyJFiQ=
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv
  -in Unity_v2020.x.ulf.enc -out ./Unity_v2020.x.ulf -d
- export UNITY_LICENSE_CONTENT=`cat Unity_v2020.x.ulf`
- rm Unity_v2020.x.ulf
- docker pull $IMAGE_NAME
jobs:
  include:
  - stage: build
    env: BUILD_TARGET=WebGL IMAGE_NAME=gableroux/unity3d:2020.1.4f1-webgl
    script: chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh && chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh
